<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Surefire suite" duration-ms="631" started-at="2018-04-20T19:58:42Z" finished-at="2018-04-20T19:58:43Z">
    <groups>
    </groups>
    <test name="Surefire test" duration-ms="631" started-at="2018-04-20T19:58:42Z" finished-at="2018-04-20T19:58:43Z">
      <class name="ca.on.oicr.pde.workflows.XenoClassifyWorkflowTest">
        <test-method status="FAIL" signature="validateRegressionTestDefinition()[pri:0, instance:ca.on.oicr.pde.workflows.XenoClassifyWorkflowTest@1f488344]" name="validateRegressionTestDefinition" duration-ms="605" started-at="2018-04-20T15:58:42Z" finished-at="2018-04-20T15:58:43Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.lang.NumberFormatException: null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.lang.NumberFormatException: null
	at ca.on.oicr.pde.workflows.XenoClassifyWorkflow.init(XenoClassifyWorkflow.java:102)
	at ca.on.oicr.pde.workflows.XenoClassifyWorkflow.setupDirectory(XenoClassifyWorkflow.java:108)
	at ca.on.oicr.pde.testing.workflow.DryRun.buildWorkflowModel(DryRun.java:67)
	at ca.on.oicr.pde.workflows.XenoClassifyWorkflowTest.validateRegressionTestDefinition(XenoClassifyWorkflowTest.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:129)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:113)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: java.lang.NumberFormatException: null
	at java.lang.Integer.parseInt(Integer.java:454)
	at java.lang.Integer.parseInt(Integer.java:527)
	at ca.on.oicr.pde.workflows.XenoClassifyWorkflow.init(XenoClassifyWorkflow.java:98)
	... 31 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateRegressionTestDefinition -->
      </class> <!-- ca.on.oicr.pde.workflows.XenoClassifyWorkflowTest -->
    </test> <!-- Surefire test -->
  </suite> <!-- Surefire suite -->
</testng-results>
