<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="oll-hdsouza" name="ca.on.oicr.pde.workflows.XenoClassifyWorkflowTest" tests="1" failures="1" timestamp="20 Apr 2018 19:58:43 GMT" time="0.605" errors="0">
  <testcase name="validateRegressionTestDefinition" time="0.605" classname="ca.on.oicr.pde.workflows.XenoClassifyWorkflowTest">
    <failure type="java.lang.RuntimeException" message="java.lang.NumberFormatException: null">
      <![CDATA[java.lang.RuntimeException: java.lang.NumberFormatException: null
	at ca.on.oicr.pde.workflows.XenoClassifyWorkflow.init(XenoClassifyWorkflow.java:102)
	at ca.on.oicr.pde.workflows.XenoClassifyWorkflow.setupDirectory(XenoClassifyWorkflow.java:108)
	at ca.on.oicr.pde.testing.workflow.DryRun.buildWorkflowModel(DryRun.java:67)
	at ca.on.oicr.pde.workflows.XenoClassifyWorkflowTest.validateRegressionTestDefinition(XenoClassifyWorkflowTest.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:129)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:113)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: java.lang.NumberFormatException: null
	at java.lang.Integer.parseInt(Integer.java:454)
	at java.lang.Integer.parseInt(Integer.java:527)
	at ca.on.oicr.pde.workflows.XenoClassifyWorkflow.init(XenoClassifyWorkflow.java:98)
	... 31 more
]]>
    </failure>
  </testcase> <!-- validateRegressionTestDefinition -->
</testsuite> <!-- ca.on.oicr.pde.workflows.XenoClassifyWorkflowTest -->
